exp:
  amount:
    combat_per_health: 0.4
    mining: 2.0
    farming: 6.0
    foraging: 4.5
  multiplier:
    combat:
      base: 1.0
      monster: 1.5
    mining:
      base: 1.0
      common_ore: 3.0
      rare_ore: 8.0
    farming:
      base: 1.0
      breeding: 1.8
    foraging:
      base: 1.0
      nether: 1.3
grinding:
  max_level: 10
  exp_to_levelup_multiplier: 1.0
  exp_booster_multiplier_per_levelup: 0.05
  perk_bonus_on_levelup:
    base: 3.0
    multiplier_for_level_bonus: 1.0
perks:
  multiplier_per_strength: 0.01
  defense_scaling_factor: 200
  vanilla_value_per_speed: 0.001